// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: ratecap/v1/ratecap.proto

package ratecapv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RatecapService_CheckRateLimit_FullMethodName = "/ratecap.v1.RatecapService/CheckRateLimit"
)

// RatecapServiceClient is the client API for RatecapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatecapServiceClient interface {
	CheckRateLimit(ctx context.Context, in *CheckRateLimitRequest, opts ...grpc.CallOption) (*CheckRateLimitResponse, error)
}

type ratecapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRatecapServiceClient(cc grpc.ClientConnInterface) RatecapServiceClient {
	return &ratecapServiceClient{cc}
}

func (c *ratecapServiceClient) CheckRateLimit(ctx context.Context, in *CheckRateLimitRequest, opts ...grpc.CallOption) (*CheckRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckRateLimitResponse)
	err := c.cc.Invoke(ctx, RatecapService_CheckRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatecapServiceServer is the server API for RatecapService service.
// All implementations must embed UnimplementedRatecapServiceServer
// for forward compatibility.
type RatecapServiceServer interface {
	CheckRateLimit(context.Context, *CheckRateLimitRequest) (*CheckRateLimitResponse, error)
	mustEmbedUnimplementedRatecapServiceServer()
}

// UnimplementedRatecapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRatecapServiceServer struct{}

func (UnimplementedRatecapServiceServer) CheckRateLimit(context.Context, *CheckRateLimitRequest) (*CheckRateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckRateLimit not implemented")
}
func (UnimplementedRatecapServiceServer) mustEmbedUnimplementedRatecapServiceServer() {}
func (UnimplementedRatecapServiceServer) testEmbeddedByValue()                        {}

// UnsafeRatecapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatecapServiceServer will
// result in compilation errors.
type UnsafeRatecapServiceServer interface {
	mustEmbedUnimplementedRatecapServiceServer()
}

func RegisterRatecapServiceServer(s grpc.ServiceRegistrar, srv RatecapServiceServer) {
	// If the following call panics, it indicates UnimplementedRatecapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RatecapService_ServiceDesc, srv)
}

func _RatecapService_CheckRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatecapServiceServer).CheckRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatecapService_CheckRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatecapServiceServer).CheckRateLimit(ctx, req.(*CheckRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RatecapService_ServiceDesc is the grpc.ServiceDesc for RatecapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatecapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ratecap.v1.RatecapService",
	HandlerType: (*RatecapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckRateLimit",
			Handler:    _RatecapService_CheckRateLimit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ratecap/v1/ratecap.proto",
}
