// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ratecap/v1/ratecap.proto

package ratecapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ALLOW      Action = 0
	Action_REJECT_429 Action = 1
	Action_REJECT_503 Action = 2
	Action_SHADOW_LOG Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ALLOW",
		1: "REJECT_429",
		2: "REJECT_503",
		3: "SHADOW_LOG",
	}
	Action_value = map[string]int32{
		"ALLOW":      0,
		"REJECT_429": 1,
		"REJECT_503": 2,
		"SHADOW_LOG": 3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ratecap_v1_ratecap_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_proto_ratecap_v1_ratecap_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_ratecap_v1_ratecap_proto_rawDescGZIP(), []int{0}
}

type CheckRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Cost          int32                  `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateLimitRequest) Reset() {
	*x = CheckRateLimitRequest{}
	mi := &file_proto_ratecap_v1_ratecap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateLimitRequest) ProtoMessage() {}

func (x *CheckRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratecap_v1_ratecap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateLimitRequest.ProtoReflect.Descriptor instead.
func (*CheckRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratecap_v1_ratecap_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRateLimitRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CheckRateLimitRequest) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type CheckRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        Action                 `protobuf:"varint,1,opt,name=action,proto3,enum=ratecap.v1.Action" json:"action,omitempty"`
	RetryAfterMs  int64                  `protobuf:"varint,2,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateLimitResponse) Reset() {
	*x = CheckRateLimitResponse{}
	mi := &file_proto_ratecap_v1_ratecap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateLimitResponse) ProtoMessage() {}

func (x *CheckRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratecap_v1_ratecap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateLimitResponse.ProtoReflect.Descriptor instead.
func (*CheckRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratecap_v1_ratecap_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRateLimitResponse) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ALLOW
}

func (x *CheckRateLimitResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

var File_proto_ratecap_v1_ratecap_proto protoreflect.FileDescriptor

const file_proto_ratecap_v1_ratecap_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/ratecap/v1/ratecap.proto\x12\n" +
	"ratecap.v1\"=\n" +
	"\x15CheckRateLimitRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\x05R\x04cost\"j\n" +
	"\x16CheckRateLimitResponse\x12*\n" +
	"\x06action\x18\x01 \x01(\x0e2\x12.ratecap.v1.ActionR\x06action\x12$\n" +
	"\x0eretry_after_ms\x18\x02 \x01(\x03R\fretryAfterMs*C\n" +
	"\x06Action\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\x0e\n" +
	"\n" +
	"REJECT_429\x10\x01\x12\x0e\n" +
	"\n" +
	"REJECT_503\x10\x02\x12\x0e\n" +
	"\n" +
	"SHADOW_LOG\x10\x032i\n" +
	"\x0eRatecapService\x12W\n" +
	"\x0eCheckRateLimit\x12!.ratecap.v1.CheckRateLimitRequest\x1a\".ratecap.v1.CheckRateLimitResponseB/Z-github.com/ratecap/proto/ratecap/v1;ratecapv1b\x06proto3"

var (
	file_proto_ratecap_v1_ratecap_proto_rawDescOnce sync.Once
	file_proto_ratecap_v1_ratecap_proto_rawDescData []byte
)

func file_proto_ratecap_v1_ratecap_proto_rawDescGZIP() []byte {
	file_proto_ratecap_v1_ratecap_proto_rawDescOnce.Do(func() {
		file_proto_ratecap_v1_ratecap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ratecap_v1_ratecap_proto_rawDesc), len(file_proto_ratecap_v1_ratecap_proto_rawDesc)))
	})
	return file_proto_ratecap_v1_ratecap_proto_rawDescData
}

var file_proto_ratecap_v1_ratecap_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ratecap_v1_ratecap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ratecap_v1_ratecap_proto_goTypes = []any{
	(Action)(0),                    // 0: ratecap.v1.Action
	(*CheckRateLimitRequest)(nil),  // 1: ratecap.v1.CheckRateLimitRequest
	(*CheckRateLimitResponse)(nil), // 2: ratecap.v1.CheckRateLimitResponse
}
var file_proto_ratecap_v1_ratecap_proto_depIdxs = []int32{
	0, // 0: ratecap.v1.CheckRateLimitResponse.action:type_name -> ratecap.v1.Action
	1, // 1: ratecap.v1.RatecapService.CheckRateLimit:input_type -> ratecap.v1.CheckRateLimitRequest
	2, // 2: ratecap.v1.RatecapService.CheckRateLimit:output_type -> ratecap.v1.CheckRateLimitResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ratecap_v1_ratecap_proto_init() }
func file_proto_ratecap_v1_ratecap_proto_init() {
	if File_proto_ratecap_v1_ratecap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ratecap_v1_ratecap_proto_rawDesc), len(file_proto_ratecap_v1_ratecap_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ratecap_v1_ratecap_proto_goTypes,
		DependencyIndexes: file_proto_ratecap_v1_ratecap_proto_depIdxs,
		EnumInfos:         file_proto_ratecap_v1_ratecap_proto_enumTypes,
		MessageInfos:      file_proto_ratecap_v1_ratecap_proto_msgTypes,
	}.Build()
	File_proto_ratecap_v1_ratecap_proto = out.File
	file_proto_ratecap_v1_ratecap_proto_goTypes = nil
	file_proto_ratecap_v1_ratecap_proto_depIdxs = nil
}
