apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  ratecap.yaml: |
{{ .Values.config.yaml | indent 4 }}
  {{- if .Values.criticalRoutes.enabled }}
  critical-routes.yaml: |
{{ .Values.criticalRoutes.yaml | indent 4 }}
  {{- end }}
