{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-core
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-core
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Release.Name }}-sidecar
      ports:
        - port: {{ .Values.core.grpcPort }}
        - port: {{ .Values.core.healthPort }}
        {{- if and .Values.tls.enabled (eq .Values.tls.mode "permissive") }}
        - port: 9443
        {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-redis
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Release.Name }}-core
      ports:
        - port: {{ .Values.redis.port }}
{{- if .Values.redis.sentinel.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-redis-sentinel
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-redis-sentinel
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Release.Name }}-core
      ports:
        - port: {{ .Values.redis.sentinel.port }}
{{- end }}
{{- end }}
